version: '3'
services:
  redis:
    image: redis:3.2
    hostname: redis
    environment:
      - TZ=Asia/Tokyo
    networks:
      - docker-php
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - docker-php
  php:
    build: php
    hostname: php
    volumes:
#      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - ./app:/app
    environment:
      - TZ=Asia/Tokyo
    extra_hosts:
      - "docker-host:10.254.254.254"
    networks:
      - docker-php
  nginx:
    build: nginx
    hostname: nginx
    ports:
      # Docker for mac unable to compose ip based connection
      # https://docs.docker.com/docker-for-mac/networking/#i-cannot-ping-my-containers
      - '8080:80'
      - '8443:443'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/config/tls:/etc/nginx/tls:ro
      - ./app:/app
    networks:
      - docker-php
networks:
  docker-php:
